services:
  app:
    build: .
    container_name: haushaltsbuch-app
#    ports:
#      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - default
      - reverseproxy_default
    environment:
      - VIRTUAL_HOST=explocal.hr-puzzle.eu
      - VIRTUAL_PORT=80
      - SELF_SIGNED_HOST=explocal.hr-puzzle.eu
      - PHP_TZ=Europe/London

  db:
    image: mariadb:10.11
    container_name: haushaltsbuch-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: haushaltsbuch
      MYSQL_USER: hauser
      MYSQL_PASSWORD: hauspass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: haushaltsbuch-pma
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default

volumes:
  db_data:

networks:
  reverseproxy_default:
    external: true
